language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-24
    - extra

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - openssl aes-256-cbc -K $encrypted_9636aa294786_key -iv $encrypted_9636aa294786_iv
    -in ./app/HappyYoung.jks.enc -out ./app/HappyYoung.jks -d

script: ./gradlew assembleRelease

before_deploy:
  - mv ./app/build/outputs/apk/app-release.apk ./TrashNetwork-Recycle-${TRAVIS_TAG}.apk
deploy:
  provider: releases
  api_key:
    secure: A8xDaK6eRUyZ/XU6UYfbs6ZpwGP+ssvPRFObSNWkg6IlToNRYr7BKZj4LDj/WNCZDTJWN3tSXk375NsoXF/tTJKQAZnRAfePzIIYB1MqUN4ULdSzmcEkiO4XHoZp10AR4muEdIXQmcqnpeQrF43gZtlati8YS7YzCY9zyAFJpi5HBJpifDai/mtpvM0NozBURLkpBHUK31ETLXE6+qV2wyP0EeKNXgBuVgHDfSXlWiH6JmeiwoVVzUd5Co+IpSbrwO8ejTP00601d5corBC72Mm7g/521WZtNZIPc6ft085hg3MgTYJ7ptPMxMXE1omgVhwyBLLK+pi76jO2Q3PAI2T6ICquIUJfoZMKFJvE+TiN5qjB8+qmjEPLyPUPOj/Wjy4btuihpDi8o2SzqdYv4DqOJBwlcbPLU3gEnAghAtb73mwmWndlnbbfAw8YweMG5G3uqMldTMnWd+5lD0Je9CPhEyiH+NSiOZi/1NcwumIblbLsL4+7wHx1S53EPKfSQYYtEyS6vq+84nHuqivyE28ycsfNSmgNLusMjnfPLd3iGW5jHvzTqoBkYj/eVu2WRtDwBpJTOKg49GJSufkvGEzePCk62MjBh2lShrZDNqMloDlCUCqcNPa/gEx2Z3+4UzPunqsfKWqwOjbCNPIpODmVW6Q3YfIupQn6HQQhoEg=
  file: 'TrashNetwork-Recycle-${TRAVIS_TAG}.apk'
  skip_cleanup: true
  on:
    tags: true
